### ISSUE TITLE
Exceptions during running zipper

### ISSUE THREAD

**Issue by april1989** [silverbullettt/zipper#1]
Hi, zipper writer, 

This is an interesting work. 

I git cloned the zipper repo and followed the instruction to build it. But I have the following exceptions when running my jars: 

bz@bz-VirtualBox:~/Documents/zipper/doop$ ./run-zipper.py -jre1.6 2-object-sensitive+heap /home/bz/Documents/zipper/doop/jars/tsp.jar
Running pre-analysis ...
Bloxbatch-Options: 
Main-Class: tsp.Tsp
Application-Classes: tsp.*
generating facts (/home/bz/Documents/zipper/doop/jars/tsp.jar /home/bz/Documents/zipper/doop/jars/empty.jar) in /home/bz/Documents/zipper/doop/cache/input-facts/jre1.6/2089a7800d152ecb119b1382cf012c92b5b7cc18f005fd34f40acbea5588eb5e/ Running JPhantom...
Exception in thread "main" java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:424)
	at jphantom.tree.ClassHierarchies.fromJar(ClassHierarchies.java:75)
	at jphantom.tree.ClassHierarchies.fromJar(ClassHierarchies.java:52)
	at jphantom.Driver.<init>(Driver.java:51)
	at jphantom.Driver.<init>(Driver.java:44)
	at jphantom.Driver.main(Driver.java:314)
JPhantom finished executing. Complement created: /home/bz/Documents/zipper/doop/tmp/tsp-complemented.jar
...
Adding archive: /home/bz/Documents/zipper/doop/tmp/tsp-complemented.jar
java.io.FileNotFoundException: /home/bz/Documents/zipper/doop/tmp/tsp-complemented.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at NoSearchingClassProvider.addArchive(NoSearchingClassProvider.java:97)
	at Main.run(Main.java:192)
	at Main.main(Main.java:174)
Command exited with non-zero status 1
0.11
Dumping doop analysis results ...
Analyze temp ...
Reading points-to analysis results ... 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ptatoolkit.zipper.Main.readPointsToAnalysis(Main.java:83)
	at ptatoolkit.zipper.Main.run(Main.java:37)
	at ptatoolkit.zipper.Main.main(Main.java:31)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at ptatoolkit.doop.factory.ObjFactory.lambda$new$0(ObjFactory.java:23)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at ptatoolkit.doop.factory.ObjFactory.<init>(ObjFactory.java:21)
	at ptatoolkit.zipper.doop.DoopPointsToAnalysis.init(DoopPointsToAnalysis.java:268)
	at ptatoolkit.zipper.doop.DoopPointsToAnalysis.<init>(DoopPointsToAnalysis.java:72)
	... 7 more
Exception in thread "main" java.lang.RuntimeException: Reading points-to analysis results fails
	at ptatoolkit.zipper.Main.readPointsToAnalysis(Main.java:90)
	at ptatoolkit.zipper.Main.run(Main.java:37)
	at ptatoolkit.zipper.Main.main(Main.java:31)
Running main (Zipper-guided) analysis ...
ERROR: Non-existent zipper file "results/temp-ZipperPrecisionCriticalMethod.facts"

Do you have any clue how to fix it? Thanks!

**Comment by silverbullettt** [comment]
Hi Bozhen, as we discussed, this problem is caused by jphantom included in Doop, and it can be avoided by specifying option "--allow-phantom".

**Comment by oren-tal** [comment]
hi :)
we are trying to run the samples that are in the artifacts that are attached in the README.
but we continue getting this error:
![image](https://github.com/silverbullettt/zipper/assets/84312836/e386ee11-458c-4bef-b98c-5a359e4e01a2)
sudo ./run.py zipper-2obj xalan
Running pre-analysis (ci) for xalan ...
/home/oren/OOPSLA18-Artifact-Zipper/artifact/doop/utils/checkenv.sh: line 13: LOGICBLOX_HOME: unbound variable
Writing all detailed client results to /home/oren/OOPSLA18-Artifact-Zipper/artifact/output-client ...
**sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found**
Dumping doop analysis results for xalan ...
Analyze xalan ...
Reading points-to analysis results ...
Zipper starts ...
Precision loss patterns: Direct+Wrapped+Unwrapped
#classes: 0

Building OFG (Object Flow Graph) ...
#nodes in OFG: 0
#edges in OFG: 0

Building PFGs (Pollution Flow Graphs) and computing precision-critical methods ...
#avg. nodes in PFG: 0
#avg. edges in PFG: 0

#Precision-critical methods: 0
Zipper finishes, analysis time: 0.02s
Writing Zipper precision-critical methods to /home/oren/OOPSLA18-Artifact-Zipper/artifact/output-zipper/xalan-ZipperPrecisionCriticalMethod.facts ...

Running Zipper-guided pointer analysis for xalan ...
/home/oren/OOPSLA18-Artifact-Zipper/artifact/doop/utils/checkenv.sh: line 13: LOGICBLOX_HOME: unbound variable
Writing all detailed client results to /home/oren/OOPSLA18-Artifact-Zipper/artifact/output-client ...
sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found
sh: 1: bloxbatch: not found

do you have any ide how to solve this?
this is the value of LOGICBLOX_HOME:
 echo $LOGICBLOX_HOME
/opt/lb/pa-datalog
thanks!
